Repository vijaygupta18/Hacktoberfest-2022, pull requests merged in 2021-10, with the labels that each got.

#262 Revert "interview notes"
  DBMS INTERVIEW NOTES/.gitignore
  DBMS INTERVIEW NOTES/DBMS.pdf
  DBMS INTERVIEW NOTES/basic sql.pdf
Labels: hacktoberfest-accepted

#261 added new html file
  HtmlTributepage/main.html
  HtmlTributepage/style.css
Labels: hacktoberfest-accepted

#260 added length of linked lists
  Data Structures/Linked list/lengthoflinkedlist.cpp
Labels: hacktoberfest-accepted

#263 Add files via upload
  primsAlgo
Labels: hacktoberfest-accepted

#264 Added Files
  djisktra
Labels: hacktoberfest-accepted, Hacktoberfest-2021

#265 Kadane's Algo added
  Algorithms/KadanesAlgorithm.java
Labels: hacktoberfest-accepted, Hacktoberfest-2021, hacktober

#266 File added
  BellmanFord
  Bfs
Labels: hacktoberfest-accepted, Hacktoberfest-2021, hacktober

#267 file added
  Dfs
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021, Hactoberfest 2021, hacktoberfest-2021

#268 file added
  bipartiteGraphBfs
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#269 files added
  KruskalAlgorithm
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktoberfest-2021

#270 added random jokes webapp
  Random-Jokes-webapp/README.md
  Random-Jokes-webapp/app.js
  Random-Jokes-webapp/gif/robot_dribbble.gif
  Random-Jokes-webapp/images/apple-touch-icon.png
  Random-Jokes-webapp/index.html
  Random-Jokes-webapp/style.css
Labels: hacktoberfest-accepted, hacktoberfest-2021

#271 Added imp question
  Algorithms/Equilbrium_Element.java
Labels: hacktoberfest-accepted

#272 sort
  Algorithms/sortAnArrayWith012.class
  Algorithms/sortAnArrayWith012.java
  FlutterFashion/android/.project
  FlutterFashion/android/.settings/org.eclipse.buildship.core.prefs
  MemeShare/.project
  MemeShare/.settings/org.eclipse.buildship.core.prefs
  bmi app/android/.project
  bmi app/android/.settings/org.eclipse.buildship.core.prefs
Labels: hacktoberfest-accepted

#273 Create prime string or no
  PYTHON/prime string or no
Labels: hacktoberfest-accepted

#277 A good login page using html and css
  login.css
  login.html
Labels: hacktoberfest-accepted

#276 adding nth catalan number in python
  Algorithms/Python/Recursion/Nth-catalan.py
Labels: hacktoberfest-accepted

#275 Face Detection using Python
  Face Detection/face_detect_cam.py
  Face Detection/haar_face.xml
  Face Detection/readme.md
Labels: hacktoberfest-accepted

#274 Create Calculator with GUI
  Calculator with GUI
Labels: hacktoberfest-accepted

#278 Registration Form Frontend
  reg form/assets/5333978.jpg
  reg form/index.html
  reg form/style.css
Labels: hacktoberfest-accepted

#280 modify readme.md and adding nth catalan number in c++
  Algorithms/Dynamic Programming/Nth-catalan.c++
  Algorithms/Dynamic Programming/Readme.md
Labels: hacktoberfest-accepted

#281 A simple 2D animation using html and CSS
  animation.css
  animation.html
Labels: hacktoberfest-accepted

#282 Create Registration page
  Registration page
Labels: hacktoberfest-accepted

#283 Web Scraping Python
  plwebsc.py
Labels: hacktoberfest-accepted, hacktoberfest-2021

#284 Added Python Code for Genetic Algorithm
  AI Genetic Algorithm/genetic_algorithm_2x^2+1_q2.py.py
Labels: hacktoberfest-accepted

#285 Back-end Registration Form in Django-Python
  Django-Registration form/simplesocial/accounts/__init__.py
  Django-Registration form/simplesocial/accounts/__pycache__/__init__.cpython-39.pyc
  Django-Registration form/simplesocial/accounts/__pycache__/admin.cpython-39.pyc
  Django-Registration form/simplesocial/accounts/__pycache__/apps.cpython-39.pyc
  Django-Registration form/simplesocial/accounts/__pycache__/forms.cpython-39.pyc
  Django-Registration form/simplesocial/accounts/__pycache__/models.cpython-39.pyc
  Django-Registration form/simplesocial/accounts/__pycache__/urls.cpython-39.pyc
  Django-Registration form/simplesocial/accounts/__pycache__/views.cpython-39.pyc
  Django-Registration form/simplesocial/accounts/admin.py
  Django-Registration form/simplesocial/accounts/apps.py
  Django-Registration form/simplesocial/accounts/forms.py
  Django-Registration form/simplesocial/accounts/migrations/0001_initial.py
  Django-Registration form/simplesocial/accounts/migrations/__init__.py
  Django-Registration form/simplesocial/accounts/migrations/__pycache__/0001_initial.cpython-39.pyc
  Django-Registration form/simplesocial/accounts/migrations/__pycache__/__init__.cpython-39.pyc
  Django-Registration form/simplesocial/accounts/models.py
  Django-Registration form/simplesocial/accounts/templates/accounts/login.html
  Django-Registration form/simplesocial/accounts/templates/accounts/signup.html
  Django-Registration form/simplesocial/accounts/tests.py
  Django-Registration form/simplesocial/accounts/urls.py
  Django-Registration form/simplesocial/accounts/views.py
  Django-Registration form/simplesocial/db.sqlite3
  Django-Registration form/simplesocial/manage.py
  Django-Registration form/simplesocial/simplesocial/__init__.py
  Django-Registration form/simplesocial/simplesocial/__pycache__/__init__.cpython-39.pyc
  Django-Registration form/simplesocial/simplesocial/__pycache__/settings.cpython-39.pyc
  Django-Registration form/simplesocial/simplesocial/__pycache__/urls.cpython-39.pyc
  Django-Registration form/simplesocial/simplesocial/__pycache__/views.cpython-39.pyc
  Django-Registration form/simplesocial/simplesocial/__pycache__/wsgi.cpython-39.pyc
  Django-Registration form/simplesocial/simplesocial/asgi.py
  Django-Registration form/simplesocial/simplesocial/settings.py
  Django-Registration form/simplesocial/simplesocial/urls.py
  Django-Registration form/simplesocial/simplesocial/views.py
  Django-Registration form/simplesocial/simplesocial/wsgi.py
  Django-Registration form/simplesocial/templates/base.html
  Django-Registration form/simplesocial/templates/index.html
  Django-Registration form/simplesocial/templates/test.html
  Django-Registration form/simplesocial/templates/thanks.html
Labels: hacktoberfest-accepted, hacktoberfest-2021

#286 Wave Sort Algo added
  Algorithms/WaveSort.java
Labels: hacktoberfest-accepted, hacktoberfest-2021

#287 Add files via upload
  Algorithms/PrimeNumber.java
Labels: hacktoberfest-accepted, hacktoberfest-2021

#289 Added Air Canvas
  Air Canvas/Trackinghandmod.py
  Air Canvas/aircanvas.py
  Air Canvas/myoptions/canvas2.png
  Air Canvas/myoptions/canvas3.png
  Air Canvas/myoptions/canvas4.png
  Air Canvas/myoptions/canvas5.png
  Air Canvas/myoptions/canvas6.png
Labels: hacktoberfest-accepted, hacktoberfest-2021

#290 Create quiz.cpp
  quiz.cpp
Labels: hacktoberfest-accepted, hacktoberfest-2021

#293 breadth first search
  BreathFirstSearch/BFS.CPP
  BreathFirstSearch/README.md
  BreathFirstSearch/Screenshot 2021-10-03 235854.png
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021, hacktoberfest-2021

#294 Contributed CoronaMap to this Repository
  CoronaMap/data.json
  CoronaMap/index.html
  CoronaMap/index.js
  Login page transparent/bg.jpg
  Login page transparent/index.css
  Login page transparent/index.html
Labels: hacktoberfest-accepted, hacktoberfest-2021

#316 Rearrange Array using MODULAR PROPERTY
  Algorithms/Rearrange_Array_Alternately.java
Labels: hacktoberfest-accepted

#311 Added Random_choice_chooser project
  Random_choice_chooser/index.html
  Random_choice_chooser/script.js
  Random_choice_chooser/style.css
Labels: hacktoberfest-accepted, hacktoberfest-2021

#320 Create 8-queens.py
  ML/8-queens.py
Labels: hacktoberfest-accepted, hacktoberfest-2021

#381 Tutorial Pascal
  C/pascal.c
Labels: hacktoberfest-accepted, hacktoberfest
